# Site settings
title: International Christian Fellowship of Budapest
email: info@icfbudapest.org
facebook: https://www.facebook.com/groups/2231582506
description: > # this means to ignore newlines until "baseurl:"
  We are a community of university students and young professionals from many
  different nationalities and backgrounds who come together in the name of Jesus
  for worship, prayer, Bible study, and service, as well as to encourage each
  other.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://icfbudapest.org" # the base hostname & protocol for your site
timezone: Europe/Budapest
logo: /img/icfbudapest.png # URL to site logo

# Build settings
markdown: kramdown
exclude: [vendor]
exclude:
- Gemfile
- Gemfile.lock
